// Generated by CoffeeScript 1.6.3
(function() {
  var myModule;

  myModule = function() {
    var myMethod;
    ({
      myProperty: "A property",
      myConfig: {
        test1: "this is test",
        test2: "this is test 2"
      }
    });
    return myMethod = 1 === 1 ? 2 + 2 : void 0;
  };

  console.dir(myModule().myProperty);

  console.dir(myModule().myConfig);

  console.log(myModule.myMethod);

}).call(this);
